intel-iot-devkit/meta-iot-cloud

ReadMe.md
Many recipes require Java. Add information for adding `meta-java` layer.
=> Add meta-java to README.

recipes-devtools/python/python-urllib3.inc, recipes-devtools/python/python-urllib3_1.21.1.bb
Move runtime dependency on python-ipaddress to python-urllib3 recipe, since this is not needed for python3-urllib3.
=> python-urllib3: python-ipaddress is only required for Python 2.x

recipes-azure/azure-c-shared-utility/azure-c-shared-utility_1.0.43.bb, recipes-azure/azure-iot-sdk/azure-iot-sdk_1.1.23.bb, recipes-azure/azure-uamqp-c/azure-uamqp-c_1.0.43.bb, recipes-azure/azure-umqtt-c/azure-umqtt-c_1.0.43.bb, recipes-support/http-parser/http-parser_2.7.0.bb
Dear Maintainers,
I added the support for Native SDK to  *http-parser* and *azure-iot-sdk* recipes.
I hope you will find it useful.
King Regards,
Gaël
=> Add support for Native-SDK to azure-iot-sdk and http-parser

recipes-support/cjson/cjson_1.4.6.bb, recipes-support/cjson/files/0001-tests-parse_hex4-Fix-GCC-7-compiler-warning-fixes-17.patch
Grab an upstream patch to address the following GCC7 build error:
cjson/1.4.6-r0/git/tests/parse_hex4.c:40:42: note: 'sprintf' output
between 5 and 6 bytes into a destination of size 5
TEST_ASSERT_EQUAL_INT_MESSAGE(4, sprintf((char*)digits_upper, "%.4X", number), "sprintf failed.");
Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
=> cjson: Fix GCC7 build issue

recipes-ibm/ibm-iotf-embeddedc/files/Add-additional-options-to-sample-apps.patch, recipes-ibm/ibm-iotf-embeddedc/ibm-iotf-embeddedc_1.0.bb
IBM IoTF Embedded C SDK: Fix certificate file not being installed for testing C samples and added option to specify config path as command line argument for Embedded C SDK samples
=> IBM IoTF Embedded C SDK: Fix for various issues

recipes-azure/iothub-explorer/node-iothub-explorer_1.1.19.bb, recipes-azure/node-red/node-red-contrib-azureiothubnode_0.1.23.bb, recipes-google-cloud/node-red-contrib-google-cloud/node-red-contrib-google-cloud_0.0.1.bb, recipes-ibm/node-red-contrib-ibm-watson-iot/node-red-contrib-ibm-watson-iot_0.2.8.bb, recipes-node-red/node-red-contrib-upm/node-red-contrib-upm_0.3.5.bb, recipes-node-red/node-red/node-red.inc
With npm 5.x and nodejs 8.x, you might see the following error:
| DEBUG: Executing shell function do_compile
| npm ERR! As of npm@5, the npm cache self-heals from corruption issues
and data extracted from the cache is guaranteed to be valid. If you want
to make sure everything is consistent, use 'npm cache verify' instead.
| npm ERR!
| npm ERR! If you're sure you want to delete the entire cache, rerun
this command with --force.
This might be a npm issue, which has been reported here:
https://github.com/npm/npm/issues/18894
So we add --force to workaround the error until upstream npm fixes it.
Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
=> Address npm cache clear error

recipes-azure/node-red/node-red-contrib-azureiothubnode_0.1.23.bb
Resolve the following error:
```ERROR: node-red-contrib-azureiothubnode-0.1.23-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.```
=> node-red-contrib-azureiothubnode: add RDEPENDS for bash

conf/layer.conf
Since `9ec5a8a layer.conf: Drop sumo from LAYERSERIES_CORENAMES' and
`9867924 layer.conf: Add thud to LAYERSERIES_CORENAMES' applied in oe-core,
update LAYERSERIES_COMPAT `sumo' -> `thud'
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
=> layer.conf: update LAYERSERIES_COMPAT `sumo' -> `thud'

recipes-support/http-parser/http-parser_2.8.1.bb
License-Update: Upstream clarified license:
Update license boilerplate.
The boilerplate included attribution to NGINX that created confusion
because NGINX is distributed under a different license (BSD, not MIT.)
To the best of everyone's knowledge, no actual NGINX code remains.
Remove the attribution to clear up the confusion.
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
=> http-parser: Update to 2.8.1

recipes-connectivity/restic/restic_0.9.5.bb
Signed-off-by: nishantpoorswani <nishantpoorswani@gmail.com>
Restic is a program which is used to backup and sync data to sftp server (via SSH), HTTP REST server (protocol rest-server), AWS S3, OpenStack Swift, BackBlaze B2, Microsoft Azure Blob Storage,
Google Cloud Storage and many more.
=> Added recipe for restic version 0.9.5

recipes-connectivity/rclone/rclone_1.49.0.bb
Rclone is used to sync data to different cloud platforms like Google Cloud, Azure, AWS S3, Alibaba cloud and many more
Signed-off-by: nishantpoorswani <nishantpoorswani@gmail.com>
=> Added recipe for Rclone version 1.49.0

recipes-aws/python/python-boto3.inc, recipes-aws/python/python-botocore.inc, recipes-aws/python/python3-s3transfer_0.2.1.bb, recipes-devtools/python/python3-jmespath_0.9.3.bb, recipes-devtools/python/python3-mapbox_0.18.0.bb
This PR adds native and nativesdk support to a number of Python recipes, and a missing RDEPENDS for botocore. Finally, it adds a new recipe for exercising the Mapbox API.
=> Misc fixes and Mapbox recipe

conf/layer.conf
poky master now supports only dunfell, so let's move up by one release.
Signed-off-by: Martin Kelly <mkelly@xevo.com>
=> layer.conf: move to next release

recipes-connectivity/openssl/openssl_1.1.1%.bbappend
Upstream appears to have fixed the static linking issue in the 1.1.1i release.
openembedded-core master and gatesgarth are on 1.1.1i, but doesn't hurt to keep it
around.
https://github.com/openssl/openssl/issues/10842
https://github.com/openssl/openssl/pull/11464
https://github.com/openssl/openssl/commit/d741debb320bf54e8575d35603a44d4eb40fa1f9
Signed-off-by: Peter Scamardo <peter.scamardo@arthrex.com>
=> openssl: Only apply this bbappend to 1.1.1g

conf/layer.conf, recipes-connectivity/openssl/openssl_1.1.1%.bbappend, recipes-connectivity/openssl/openssl_1.1.1g.bbappend
To prevent dangling append errors, perform the detection inside the
SRC_URI, mirrors f9b0f81 on gatesgarth.
Also, remove the temporary override in 8deeed3
=> openssl: Apply patch to 1.1.1f/g/h

recipes-aws/python/python-botocore.inc
31b79a2ccb split the RDEPNDS block into two but instead of extending the first block the second block overwrites it
This means that needed dependencies such as python-unixadmin are missed
Fixes: #84
=> botocore: fix RDEPENDS

recipes-aws/aws-c-auth/aws-c-auth_0.5.2.bb, recipes-aws/aws-c-cal/aws-c-cal_0.5.6.bb, recipes-aws/aws-c-common/aws-c-common_0.5.11.bb, recipes-aws/aws-c-compression/aws-c-compression_0.2.11.bb, recipes-aws/aws-c-event-stream/aws-c-event-stream_0.2.7.bb, recipes-aws/aws-c-http/aws-c-http_0.6.4.bb, recipes-aws/aws-c-io/aws-c-io_0.9.9.bb, recipes-aws/aws-c-iot/aws-c-iot_0.0.5.bb, recipes-aws/aws-c-mqtt/aws-c-mqtt_0.7.6.bb, recipes-aws/aws-c-s3/aws-c-s3_0.1.16.bb, recipes-aws/aws-checksums/aws-checksums_0.1.11.bb, recipes-aws/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.12.6.bb, recipes-aws/python/python3-awscrt_0.11.20.bb, recipes-aws/s2n/s2n_1.0.5.bb
The tag=v${PV} in SRC_URI doesn't work when add the git sources such as
github.com.awslabs.aws-c-cal.git to PREMIRRORS and set BB_NO_NETWORK = "1":
$ bitbake aws-c-cal -cfetch
ERROR: aws-c-cal-0.5.6-r0 do_fetch: Network access disabled through BB_NO_NETWORK (or set indirectly due to use of BB_FETCH_PREMIRRORONLY) but access requested with command git -c core.fsyncobjectfiles=0 ls-remote git://github.com/awslabs/aws-c-cal.git  (for url git://github.com/awslabs/aws-c-cal.git)
This is because there is no SRCREV, and bitbake needs check the original url to
get it. And we can't set both tag and SRCREV since bitbake would report that as
conflicts, and compared to SRCREV, tag is not reliable enough since it can be
recreated, so use SRCREV to replace tag.
Signed-off-by: Robert Yang …
=> recipes-aws: Use SRCREV to replace tag

recipes-azure/azure-macro-utils-c/azure-macro-utils-c.inc
build main package to satisfy -dev dependency
Signed-off-by: Saul Wold <saul.wold@windriver.com>
=> azure-macro-utils-c: Allow empty base package

recipes-aws/aws-c-common/aws-c-common/0001-priority_queue.c-fix-compile-error-with-Og.patch, recipes-aws/aws-c-common/aws-c-common_0.5.11.bb
Fix build error with -Og for aws-c-common.
Signed-off-by: Kai Kang <kai.kang@windriver.com>
=> aws-c-common: fix build error with -Og

recipes-aws/s2n/s2n_0.10.19.bb, recipes-connectivity/rclone/rclone_1.53.1.bb, recipes-connectivity/restic/restic_0.10.0.bb, recipes-support/crc32c/crc32c_1.0.6.bb
Now all recipes on hardknott branch use SRCREV
=> hardknott: Fix do_fetch error for crc32c and use SRCREV to replace tag

recipes-aws/python/python3-awscrt_0.10.8.bb
Previous commit to fix build error with multilib broke non-multilib
build if usrmerge is enabled in DISTRO_FEATURES.
Signed-off-by: Geoff Parker <geoffrey.parker@arthrex.com>
=> python3-awscrt: Fix build error if DISTRO_FEATURES has usrmerge enabled

recipes-azure/azure-c-shared-utility/azure-c-shared-utility.inc, recipes-azure/azure-c-shared-utility/files/0001-Fix-openssl-3.x-compatibility.patch, recipes-azure/azure-c-shared-utility/files/Use-pkg-config-to-find-libs.patch, recipes-core/packagegroups/packagegroup-cloud-azure_0.20.bb
For azure-c-shared-utility, upstream don't support OpenSSL 3.0.
at the moment [1], we have to workaround it by still using deprecated
functions in openssl 3.x
[1] https://github.com/Azure/azure-c-shared-utility/issues/565
=> Fix openssl 3.x compatibility

recipes-support/crc32c/crc32c_1.0.6.bb
The SRC_URI branch name has changed, and bitbake doesn't like the tag. The hardknott branch uses SRCREV, I'm guessing that is the preferred way to do it? I'm using the kirkstone branch, but the same should apply to main as well.
=> crc32c: Fix branch name, replace tag with SRCREV

recipes-azure/python/python3-azure-iot-device/0001-setup.py-fit-new-setuptools.patch, recipes-azure/python/python3-azure-iot-device_2.3.0.bb
We get the following error at build.
error in azure-iot-device setup command: 'python_requires'
must be a string containing valid version specifiers; Invalid specifier: '!=3.3*'
This is because new setuptools does not allow such specifier. Change to use >=3.4 to fix this issue.
=> python3-azure-iot-cloud: fix do_compile error with new setuptools

recipes-devtools/node-red/node-red_3.0.2.bb
* npm.bbclass copies the 'lib' into nonarch_libdir not regular libdir: https://git.openembedded.org/openembedded-core/tree/meta/classes-recipe/npm.bbclass?h=scarthgap#n310
* on builds where libdir != nonarch_libdir (e.g. with multilib) this fails, because build-tmp-napi-v3 wasn't removed in do_install:
ERROR: QA Issue: Symlink /usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/node_gyp_bins/python3 in node-red points to TMPDIR [symlink-to-sysroot]
ERROR: QA Issue: non -staticdev package contains static .a library: node-red path '/usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/Release/nothing.a'
non -staticdev package contains static .a library: node-red path '/usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/Release/node-addon-api/n …
=> node-red: remove temporary files from correct directory

recipes-azure/azure-iot-sdk-c/azure-iot-sdk-c_git.bb, recipes-connectivity/rclone/rclone_1.66.0.bb, recipes-devtools/python/python3-libcst_1.3.1.bb, recipes-google-cloud/google-cloud-cpp/google-cloud-cpp_2.23.0.bb, recipes-support/crc32c/crc32c_1.1.2.bb, recipes-support/nlohmann-json/nlohmann-json_3.11.3.bb
It fails to parse the recipes which use `tag` option in SRC_URI, such as
| ERROR: ExpansionError during parsing meta-iot-cloud/recipes-azure/azure-iot-sdk-c/azure-iot-sdk-c_git.bb |
| The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]
Remove the option `tag` and SRC_URI and add SRCREV for each recipe to fix the errors.
=> Fix parse errors caused by SRC_URI

recipes-azure/azure-c-shared-utility/azure-c-shared-utility_git.bb, recipes-azure/azure-c-shared-utility/files/CVE-2024-29195.patch
CVE-2024-29195:
The azure-c-shared-utility is a C library for AMQP/MQTT communication to Azure Cloud Services. This library may be used by the Azure IoT C SDK for communication between IoT Hub and IoT Hub devices. An attacker can cause an integer wraparound or under-allocation or heap buffer overflow due to vulnerabilities in parameter checking mechanism, by exploiting the buffer length parameter in Azure C SDK, which may lead to remote code execution. Requirements for RCE are 1. Compromised Azure account allowing malformed payloads to be sent to the device via IoT Hub service, 2. By passing IoT hub service max message payload limit of 128KB, and 3. Ability to overwrite code space with remote code. Fixed in commit
https://github.com/Azure/azure-c-shared-utility/commit/1129147c38ac02ad974c4 …
=> azure-c-shared-utility: fix CVE-2024-29195
